# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.config import concat_string_vars as concat_string_vars
from ecoscope.platform.tasks.config import (
    default_if_string_is_empty as default_if_string_is_empty,
)
from ecoscope.platform.tasks.config import get_bounding_box as get_bounding_box
from ecoscope.platform.tasks.config import (
    get_filter_point_coords as get_filter_point_coords,
)
from ecoscope.platform.tasks.config import get_segment_filter as get_segment_filter
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_traj_filters as set_traj_filters
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    get_event_type_display_names_from_events as get_event_type_display_names_from_events,
)
from ecoscope.platform.tasks.io import (
    get_patrol_observations_from_patrols_df_and_combined_params as get_patrol_observations_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.io import (
    get_patrols_from_combined_params as get_patrols_from_combined_params,
)
from ecoscope.platform.tasks.io import (
    get_spatial_features_group as get_spatial_features_group,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import process_events_details as process_events_details
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    all_keyed_iterables_are_skips as all_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_spatial_index as add_spatial_index,
)
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    align_keyed_iterable_to_reference as align_keyed_iterable_to_reference,
)
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope.platform.tasks.transformation import (
    extract_spatial_grouper_feature_group_names as extract_spatial_grouper_feature_group_names,
)
from ecoscope.platform.tasks.transformation import fill_na as fill_na
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope.platform.tasks.transformation import (
    resolve_spatial_feature_groups_for_spatial_groupers as resolve_spatial_feature_groups_for_spatial_groupers,
)
from ecoscope.platform.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_custom.tasks.config import (
    call_meshgrid_from_map_options as call_meshgrid_from_map_options,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_agg_column_from_map_options as get_agg_column_from_map_options,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_base_maps_from_map_options as get_base_maps_from_map_options,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_mask_threshold_from_map_options as get_mask_threshold_from_map_options,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    set_encounter_rate_map_options as set_encounter_rate_map_options,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    calculate_encounter_rate_grid as calculate_encounter_rate_grid,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    drop_inactive_grid_cells as drop_inactive_grid_cells,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    mask_low_effort_cells as mask_low_effort_cells,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    er_patrol_and_events_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("er_patrol_and_events_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            truncate_to_time_range=True,
            sub_page_size=100,
            patrols_overlap_daterange=True,
            include_null_geometry=False,
            **(params.get("er_patrol_and_events_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        task(get_patrols_from_combined_params)
        .validate()
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=er_patrol_and_events_params,
            **(params.get("prefetch_patrols") or {}),
        )
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_and_events_params,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    patrol_events = (
        task(unpack_events_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_and_events_params,
            **(params.get("patrol_events") or {}),
        )
        .call()
    )

    event_type_display_names = (
        task(get_event_type_display_names_from_events)
        .validate()
        .set_task_instance_id("event_type_display_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            events_gdf=patrol_events,
            append_category_names="duplicates",
            **(params.get("event_type_display_names") or {}),
        )
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    convert_patrols_to_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_to_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_patrols_to_tz") or {}),
        )
        .call()
    )

    convert_events_to_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_to_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=event_type_display_names,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_to_tz") or {}),
        )
        .call()
    )

    patrol_filters = (
        task(set_traj_filters)
        .validate()
        .set_task_instance_id("patrol_filters")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_filters") or {}))
        .call()
    )

    bounding_box = (
        task(get_bounding_box)
        .validate()
        .set_task_instance_id("bounding_box")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("bounding_box") or {}))
        .call()
    )

    filter_point_coords = (
        task(get_filter_point_coords)
        .validate()
        .set_task_instance_id("filter_point_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("filter_point_coords") or {}))
        .call()
    )

    segment_filter = (
        task(get_segment_filter)
        .validate()
        .set_task_instance_id("segment_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("segment_filter") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    spatial_group_ids = (
        task(extract_spatial_grouper_feature_group_names)
        .validate()
        .set_task_instance_id("spatial_group_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=groupers, **(params.get("spatial_group_ids") or {}))
        .call()
    )

    fetch_all_spatial_feature_groups = (
        task(get_spatial_features_group)
        .validate()
        .set_task_instance_id("fetch_all_spatial_feature_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            **(params.get("fetch_all_spatial_feature_groups") or {}),
        )
        .map(argnames=["spatial_features_group_name"], argvalues=spatial_group_ids)
    )

    resolved_groupers = (
        task(resolve_spatial_feature_groups_for_spatial_groupers)
        .validate()
        .set_task_instance_id("resolved_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=groupers,
            spatial_feature_groups=fetch_all_spatial_feature_groups,
            **(params.get("resolved_groupers") or {}),
        )
        .call()
    )

    drop_extra_prefix_obs = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_to_tz,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_obs") or {}),
        )
        .call()
    )

    filter_patrol_obs = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_obs,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            **(params.get("filter_patrol_obs") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_patrol_obs,
            trajectory_segment_filter=segment_filter,
            **(params.get("patrol_traj") or {}),
        )
        .call()
    )

    drop_extra_prefix_traj = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_traj") or {}),
        )
        .call()
    )

    customize_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("customize_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_traj,
            rename_columns={},
            drop_columns=["id"],
            retain_columns=[],
            raise_if_not_found=False,
            duplicate_strategy="suffix",
            **(params.get("customize_columns") or {}),
        )
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=customize_columns,
            time_col="segment_start",
            groupers=resolved_groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    traj_rename_grouper_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_rename_grouper_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_temporal_index,
            drop_columns=["patrol_type"],
            retain_columns=[],
            raise_if_not_found=False,
            rename_columns={"patrol_type__value": "patrol_type"},
            duplicate_strategy="suffix",
            **(params.get("traj_rename_grouper_cols") or {}),
        )
        .call()
    )

    traj_add_spatial_index = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("traj_add_spatial_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=traj_rename_grouper_cols,
            groupers=resolved_groupers,
            **(params.get("traj_add_spatial_index") or {}),
        )
        .call()
    )

    drop_extra_prefix_events = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_to_tz,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_events") or {}),
        )
        .call()
    )

    process_event_details = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("process_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_events,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_event_details") or {}),
        )
        .call()
    )

    normalize_event_details = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_event_details,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=False,
            **(params.get("normalize_event_details") or {}),
        )
        .call()
    )

    drop_event_details_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_event_details_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_event_details,
            prefix="event_details__",
            duplicate_strategy="suffix",
            **(params.get("drop_event_details_prefix") or {}),
        )
        .call()
    )

    filter_patrol_events = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_events,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            **(params.get("filter_patrol_events") or {}),
        )
        .call()
    )

    pe_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("pe_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_patrol_events,
            time_col="patrol_start_time",
            groupers=resolved_groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("pe_add_temporal_index") or {}),
        )
        .call()
    )

    pe_add_spatial_index = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("pe_add_spatial_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=pe_add_temporal_index,
            groupers=resolved_groupers,
            **(params.get("pe_add_spatial_index") or {}),
        )
        .call()
    )

    traj_cols_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("traj_cols_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_spatial_index,
            columns=["patrol_serial_number", "patrol_type"],
            **(params.get("traj_cols_to_string") or {}),
        )
        .call()
    )

    pe_cols_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("pe_cols_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pe_add_spatial_index,
            columns=["patrol_serial_number", "patrol_type"],
            **(params.get("pe_cols_to_string") or {}),
        )
        .call()
    )

    split_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_cols_to_string,
            groupers=resolved_groupers,
            **(params.get("split_traj_groups") or {}),
        )
        .call()
    )

    split_pe_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_pe_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pe_cols_to_string,
            groupers=resolved_groupers,
            **(params.get("split_pe_groups") or {}),
        )
        .call()
    )

    aligned_split_pe_groups = (
        task(align_keyed_iterable_to_reference)
        .validate()
        .set_task_instance_id("aligned_split_pe_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            target=split_pe_groups,
            reference=split_traj_groups,
            **(params.get("aligned_split_pe_groups") or {}),
        )
        .call()
    )

    map_options = (
        task(set_encounter_rate_map_options)
        .validate()
        .set_task_instance_id("map_options")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(intersecting_only=True, **(params.get("map_options") or {}))
        .call()
    )

    agg_column = (
        task(get_agg_column_from_map_options)
        .validate()
        .set_task_instance_id("agg_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(options=map_options, **(params.get("agg_column") or {}))
        .call()
    )

    details_agg_subset = (
        task(map_columns)
        .validate()
        .set_task_instance_id("details_agg_subset")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_event_details_prefix,
            rename_columns={},
            drop_columns=[],
            retain_columns=["id", agg_column],
            raise_if_not_found=False,
            duplicate_strategy="suffix",
            **(params.get("details_agg_subset") or {}),
        )
        .call()
    )

    pe_groups_with_agg = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("pe_groups_with_agg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            right=details_agg_subset,
            how="left",
            on="id",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("pe_groups_with_agg") or {}),
        )
        .mapvalues(argnames=["left"], argvalues=aligned_split_pe_groups)
    )

    zipped_events_traj = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zipped_events_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                all_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[pe_groups_with_agg, split_traj_groups],
            **(params.get("zipped_events_traj") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(get_base_maps_from_map_options)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(options=map_options, **(params.get("base_map_defs") or {}))
        .call()
    )

    encounter_meshgrid = (
        task(call_meshgrid_from_map_options)
        .validate()
        .set_task_instance_id("encounter_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=traj_cols_to_string,
            options=map_options,
            **(params.get("encounter_meshgrid") or {}),
        )
        .call()
    )

    encounter_rate_grid = (
        task(calculate_encounter_rate_grid)
        .validate()
        .set_task_instance_id("encounter_rate_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            meshgrid=encounter_meshgrid,
            sum_column=agg_column,
            **(params.get("encounter_rate_grid") or {}),
        )
        .mapvalues(argnames=["feature_layers"], argvalues=zipped_events_traj)
    )

    drop_inactive_cells = (
        task(drop_inactive_grid_cells)
        .validate()
        .set_task_instance_id("drop_inactive_cells")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event_column="event_count",
            patrol_effort_column="patrol_effort_km",
            **(params.get("drop_inactive_cells") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=encounter_rate_grid)
    )

    fill_nan_rate = (
        task(fill_na)
        .validate()
        .set_task_instance_id("fill_nan_rate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(columns=["density"], value=0, **(params.get("fill_nan_rate") or {}))
        .mapvalues(argnames=["df"], argvalues=drop_inactive_cells)
    )

    sort_rate_values = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sort_rate_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="density",
            ascending=True,
            na_position="last",
            **(params.get("sort_rate_values") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=fill_nan_rate)
    )

    classify_rate = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("classify_rate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density",
            output_column_name="rate_bins",
            classification_options={"scheme": "equal_interval", "k": 10},
            label_options={"label_ranges": True, "label_decimals": 2},
            **(params.get("classify_rate") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sort_rate_values)
    )

    rate_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("rate_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="rate_bins",
            colormap="RdYlGn_r",
            output_column_name="rate_colormap",
            **(params.get("rate_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=classify_rate)
    )

    mask_threshold = (
        task(get_mask_threshold_from_map_options)
        .validate()
        .set_task_instance_id("mask_threshold")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(options=map_options, **(params.get("mask_threshold") or {}))
        .call()
    )

    mask_low_effort = (
        task(mask_low_effort_cells)
        .validate()
        .set_task_instance_id("mask_low_effort")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrol_effort_column="patrol_effort_km",
            color_column="rate_colormap",
            label_column="rate_bins",
            threshold_km=mask_threshold,
            grey_color=[128, 128, 128, 255],
            grey_label="< 200 m patrol effort",
            **(params.get("mask_low_effort") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=rate_colormap)
    )

    rate_numerator_label = (
        task(default_if_string_is_empty)
        .validate()
        .set_task_instance_id("rate_numerator_label")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value=agg_column,
            default="Events",
            **(params.get("rate_numerator_label") or {}),
        )
        .call()
    )

    rate_col_label = (
        task(concat_string_vars)
        .validate()
        .set_task_instance_id("rate_col_label")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            values=[rate_numerator_label, " per km"],
            **(params.get("rate_col_label") or {}),
        )
        .call()
    )

    rename_rate_col = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_rate_col")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "density": rate_col_label,
                "event_count": "Events",
                "event_sum": rate_numerator_label,
                "patrol_effort_km": "Patrol Effort (km)",
            },
            duplicate_strategy="suffix",
            raise_if_not_found=False,
            **(params.get("rename_rate_col") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=mask_low_effort)
    )

    rate_polygon_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("rate_polygon_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "rate_colormap",
                "get_line_width": 0,
                "opacity": 0.4,
            },
            legend={"label_column": "rate_bins", "color_column": "rate_colormap"},
            tooltip_columns=[
                rate_col_label,
                rate_numerator_label,
                "Patrol Effort (km)",
            ],
            **(params.get("rate_polygon_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=rename_rate_col)
    )

    set_rate_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_rate_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Encounter Rate Map", **(params.get("set_rate_map_title") or {}))
        .call()
    )

    rate_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("rate_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": rate_col_label,
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_rate_map_title,
            **(params.get("rate_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=rate_polygon_layer)
    )

    rate_ecomap_html_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("rate_ecomap_html_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="encounter_rate_map",
            **(params.get("rate_ecomap_html_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=rate_ecomap)
    )

    rate_map_widgets = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("rate_map_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_rate_map_title, **(params.get("rate_map_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=rate_ecomap_html_urls)
    )

    grouped_rate_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_rate_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=rate_map_widgets, **(params.get("grouped_rate_map_widget") or {})
        )
        .call()
    )

    encounter_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("encounter_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[grouped_rate_map_widget],
            groupers=resolved_groupers,
            time_range=time_range,
            **(params.get("encounter_dashboard") or {}),
        )
        .call()
    )

    return encounter_dashboard
